// Backend/models/Video.js
const mongoose = require('mongoose');

// ─────────────────────────────────────────────────────────────────────────────
// SUB-SCHEMAS
// ─────────────────────────────────────────────────────────────────────────────

const viewSchema = new mongoose.Schema({
  userId:    { type: mongoose.Schema.Types.ObjectId, ref: 'User' },
  watchTime: { type: Number, default: 0 },   // seconds actually watched
  viewedAt:  { type: Date,   default: Date.now },
}, { _id: false });

const reportSchema = new mongoose.Schema({
  userId:      { type: mongoose.Schema.Types.ObjectId, ref: 'User', required: true },
  reason: {
    type: String,
    enum: ['spam', 'harassment', 'hate_speech', 'violence', 'misinformation', 'copyright', 'other'],
    required: true,
  },
  description: { type: String, trim: true, maxlength: 500, default: '' },
  reportedAt:  { type: Date, default: Date.now },
}, { _id: true });

// ─────────────────────────────────────────────────────────────────────────────
// MAIN VIDEO SCHEMA
// ─────────────────────────────────────────────────────────────────────────────

const videoSchema = new mongoose.Schema({

  // ── Ownership ──────────────────────────────────────────────────────────────
  userId: {
    type:     mongoose.Schema.Types.ObjectId,
    ref:      'User',
    required: [true, 'User ID is required'],
    index:    true,
  },

  // ── Core Content ──────────────────────────────────────────────────────────
  title: {
    type:      String,
    required:  [true, 'Title is required'],
    trim:      true,
    maxlength: [150, 'Title cannot exceed 150 characters'],
  },
  description: {
    type:      String,
    trim:      true,
    maxlength: [2200, 'Description cannot exceed 2200 characters'],
    default:   '',
  },
  song: {
    type:    String,
    trim:    true,
    default: '',   // e.g. "Original Sound – username"
  },
  tags: [{
    type:      String,
    trim:      true,
    lowercase: true,
  }],
  category: {
    type:    String,
    enum:    ['entertainment', 'education', 'music', 'sports', 'gaming', 'food', 'travel', 'fashion', 'tech', 'other'],
    default: 'other',
  },

  // ── Cloudinary – Video ─────────────────────────────────────────────────────
  videoUrl:        { type: String, required: [true, 'Video URL is required'] },
  videoPublicId:   { type: String, required: [true, 'Cloudinary public ID is required'] },

  // ── Cloudinary – Thumbnail ─────────────────────────────────────────────────
  thumbnailUrl:      { type: String, default: '' },
  thumbnailPublicId: { type: String, default: '' },

  // ── Media Metadata ─────────────────────────────────────────────────────────
  duration:  { type: Number, default: 0 },         // seconds
  fileSize:  { type: Number, default: 0 },         // bytes
  format:    { type: String, default: '' },        // mp4, mov, etc.
  resolution: {
    width:  { type: Number, default: 0 },
    height: { type: Number, default: 0 },
  },

  // ── Visibility & Status ───────────────────────────────────────────────────
  visibility: {
    type:    String,
    enum:    ['public', 'private', 'followers'],
    default: 'public',
  },
  status: {
    type:    String,
    enum:    ['processing', 'active', 'deleted', 'suspended'],
    default: 'processing',
  },

  // ── Permissions ───────────────────────────────────────────────────────────
  allowDownload: { type: Boolean, default: true  },
  allowComments: { type: Boolean, default: true  },
  allowDuet:     { type: Boolean, default: true  },

  // ── Social Arrays (store userId refs) ────────────────────────────────────
  likes:          [{ type: mongoose.Schema.Types.ObjectId, ref: 'User' }],
  saves:          [{ type: mongoose.Schema.Types.ObjectId, ref: 'User' }],
  reposts:        [{ type: mongoose.Schema.Types.ObjectId, ref: 'User' }],
  favorites:      [{ type: mongoose.Schema.Types.ObjectId, ref: 'User' }],
  notInterested:  [{ type: mongoose.Schema.Types.ObjectId, ref: 'User' }],

  // ── Denormalized Counters (fast reads for feed) ──────────────────────────
  likesCount:     { type: Number, default: 0 },
  commentsCount:  { type: Number, default: 0 },
  savesCount:     { type: Number, default: 0 },
  repostsCount:   { type: Number, default: 0 },
  sharesCount:    { type: Number, default: 0 },
  viewsCount:     { type: Number, default: 0 },
  downloadsCount: { type: Number, default: 0 },
  favoritesCount: { type: Number, default: 0 },

  // ── Views Log (unique per user) ──────────────────────────────────────────
  views: [viewSchema],

  // ── Multi-quality URLs (generated by Cloudinary eager transformations) ──────
  qualities: {
    '144p': { type: String, default: '' },
    '240p': { type: String, default: '' },
    '360p': { type: String, default: '' },
    '480p': { type: String, default: '' },
    '720p': { type: String, default: '' },
  },

  // ── Pinned Comment ────────────────────────────────────────────────────────
  pinnedComment: {
    type:    mongoose.Schema.Types.ObjectId,
    ref:     'Comment',
    default: null,
  },

  // ── Reports ───────────────────────────────────────────────────────────────
  reports:      [reportSchema],
  reportCount:  { type: Number, default: 0 },
  isReported:   { type: Boolean, default: false },

}, { timestamps: true });

// ─────────────────────────────────────────────────────────────────────────────
// INDEXES  (compound indexes for common query patterns)
// ─────────────────────────────────────────────────────────────────────────────
videoSchema.index({ status: 1, visibility: 1, createdAt: -1 });
videoSchema.index({ userId: 1, status: 1, createdAt: -1 });
videoSchema.index({ tags: 1, createdAt: -1 });
videoSchema.index({ category: 1, createdAt: -1 });
videoSchema.index({ viewsCount: -1 });
videoSchema.index({ likesCount: -1 });

// ─────────────────────────────────────────────────────────────────────────────
// INSTANCE HELPERS
// ─────────────────────────────────────────────────────────────────────────────
videoSchema.methods.isLikedBy      = function (uid) { return this.likes.some(id => id.equals(uid)); };
videoSchema.methods.isSavedBy      = function (uid) { return this.saves.some(id => id.equals(uid)); };
videoSchema.methods.isRepostedBy   = function (uid) { return this.reposts.some(id => id.equals(uid)); };
videoSchema.methods.isFavoritedBy  = function (uid) { return this.favorites.some(id => id.equals(uid)); };
videoSchema.methods.hasViewedBy    = function (uid) { return this.views.some(v => v.userId && v.userId.equals(uid)); };

module.exports = mongoose.model('Video', videoSchema);
